### ISSUE TITLE
activities-list vtable styling is a bit wonky due to Emacs default styling

### ISSUE THREAD

**Issue by shipmints** [alphapapa/activities.el#104]
Perhaps this is simply a documentation issue for ```activities-list``` users. Now that ```vtable``` is "standard," you'd think common themes such as ```modus-themes``` would have styling support. The default style is variable-width font and not easily readable (at least not by me).

I use this stanza in my configuration:

```elisp
(use-package modus-themes
...
  (defun my/modus-themes-after-load-theme-hook (&rest _)
...
    (defface vtable `((t :inherit #'header-line)) "")
...
```

Perhaps this helps someone. Request for official ```vtable``` support in ```modus-themes```: https://github.com/protesilaos/modus-themes/issues/110

**Comment by alphapapa** [comment]
Vtable is defined to use the `vtable` face by default, which is defined to inherit from `variable-pitch` by default.  This was a design choice by Vtable's author.  I doubt that themes should override that.  Instead, users can customize the `vtable` or `variable-pitch` faces accordingly, or authors can use a different face when making a vtable.

**Comment by shipmints** [comment]
Lars had several itches to scratch when contributing ```vtable```. One was that ```tabulated-list-mode``` is kinda shite, another was it didn't look good with variable-pitch fonts. It wasn't dedicated to variable pitch, just a scratch.
