### ISSUE TITLE
Calling activities-list when there are no activities causes an error

### ISSUE THREAD

**Issue by fuzy112** [alphapapa/activities.el#11]
Here is the backtrace:

<details><summary>Details</summary>
<p>

Debugger entered--Lisp error: (wrong-number-of-arguments #<subr max> 0)
  max()
  apply(max nil)
  seq-max(nil)
  #f(compiled-function (column index) #<bytecode -0x1ca768627d88b573>)(#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) 0)
  #f(compiled-function (elt) #<bytecode -0x13aa50143314c409>)(#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t))
  mapcar(#f(compiled-function (elt) #<bytecode -0x13aa50143314c409>) (#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Name" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (object _table) (activities-activity-name object)) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Last saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t) #s(vtable-column :name "Default saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t)))
  #f(compiled-function #'sequence #<bytecode 0x18576f7298331fb4>)(#f(compiled-function (elt) #<bytecode -0x13aa50143314c409>) (#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Name" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (object _table) (activities-activity-name object)) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Last saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t) #s(vtable-column :name "Default saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t)))
  apply(#f(compiled-function #'sequence #<bytecode 0x18576f7298331fb4>) #f(compiled-function (elt) #<bytecode -0x13aa50143314c409>) (#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Name" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (object _table) (activities-activity-name object)) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Last saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t) #s(vtable-column :name "Default saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t)) nil)
  seq-map(#f(compiled-function (elt) #<bytecode -0x13aa50143314c409>) (#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Name" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (object _table) (activities-activity-name object)) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Last saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t) #s(vtable-column :name "Default saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t)))
  seq-map-indexed(#f(compiled-function (column index) #<bytecode -0x1ca768627d88b573>) (#s(vtable-column :name "Active" :width nil :min-width nil :max-width nil :primary descend :align right :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " ")) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Name" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (object _table) (activities-activity-name object)) :formatter nil :displayer nil :-numerical t) #s(vtable-column :name "Last saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t) #s(vtable-column :name "Default saved" :width nil :min-width nil :max-width nil :primary nil :align right :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time :displayer nil :-numerical t)))
  vtable--compute-widths(#<vtable vtable-292abcc> nil)
  vtable--recompute-cache(#<vtable vtable-292abcc>)
  vtable--ensure-cache(#<vtable vtable-292abcc>)
  vtable-insert(#<vtable vtable-292abcc>)
  make-vtable(:columns ((:name "Active" :primary descend :getter (lambda (object _table) (if (activities-activity-active-p object) "*" " "))) (:name "Name" :getter (lambda (object _table) (activities-activity-name object))) (:name "Last saved" :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-last activity)) 'time) 0)) :formatter activities-list--format-time) (:name "Default saved" :getter (lambda (activity _table) (or (map-elt (activities-activity-state-etc (activities-activity-default activity)) 'time) 0)) :formatter activities-list--format-time)) :objects-function #f(compiled-function () #<bytecode 0x1980f6ff483e>) :sort-by ((2 . ascend) (0 . descend)) :actions ("q" (lambda (&rest _) (bury-buffer)) "n" (lambda (&rest _) (forward-line 1)) "p" (lambda (&rest _) (forward-line -1)) "RET" #f(compiled-function (&rest args) #<bytecode 0xbe6dddefbe4b752>) "k" #f(compiled-function (&rest args) #<bytecode 0xbe6ddd48725af52>) "s" #f(compiled-function (&rest args) #<bytecode 0xbe6ddd487256352>) "D" #f(compiled-function (&rest args) #<bytecode 0xbe6ddd7899e4352>)))
  activities-list()
  funcall-interactively(activities-list)
  command-execute(activities-list)

</p>
</details>

**Comment by alphapapa** [comment]
Thanks.
