### ISSUE TITLE
How to delete an activity?

### ISSUE THREAD

**Issue by linwaytin** [alphapapa/activities.el#122]
Amazing package! It solves two of my problems together.

I have a stupid question. How can I totally delete an activity? I ask because I created a few activities for test, but now I don't know how to get rid of them lol.

Thanks a lot.

**Comment by alphapapa** [comment]
I'm glad it's useful to you.  The word you're looking for in the documentation is "discard."  ;)

**Comment by linwaytin** [comment]
Thank you!

**Comment by pedro-nonfree** [comment]
I spent some days using this and I thought delete or remove was not possible. Then I found this issue. Now the doubt is solved on my side, but for next users:

I think there is no definition that discard means remove/delete; what if the documentation says, in the definition of `activities-discard`, something like:

> Discard an activity permanently, hence remove or delete the activity.
