### ISSUE TITLE
activities-tab-face overrides tab-bar and tab-bar-inactive faces

### ISSUE THREAD

**Issue by ericsfraga** [alphapapa/activities.el#15]
I use the :foreground attribute of tab-bar and tab-bar-inactive faces to highlight the active tab. The activities package overrides this making all the activities tabs not only look different to the other tabs (which is okay, I guess, but not necessary for me) but makes it impossible for me to know which is the active tab.

I am not sure how to get around this. I tried setting the activities-tab-face to an empty list in my theme but that just makes it default to the default face (for some unknown reason). Any suggestions welcome!

Thank you for an otherwise very interesting and useful package.

**Comment by alphapapa** [comment]
Hi Eric,

> I use the :foreground attribute of tab-bar and tab-bar-inactive faces to highlight the active tab. The activities package overrides this making all the activities tabs not only look different to the other tabs (which is okay, I guess, but not necessary for me) but makes it impossible for me to know which is the active tab.

Understandable.  I'm using Prot's `modus` and `ef` themes, and the foreground doesn't change between various types of tab, so using it to indicate activity association works for me.
 
> I am not sure how to get around this. I tried setting the activities-tab-face to an empty list in my theme but that just makes it default to the default face (for some unknown reason). Any suggestions welcome!

I don't know why that would be the case.  Just now, I tested redefining the face like this:
```elisp
(defface activities-tabs-face
  `((t  nil))
  "Applied to tab-bar faces for tabs representing activities.")
```
Which shows up in the customization buffer as:
```
Activities Tabs Face:[sample]
    State : STANDARD.
   Applied to tab-bar faces for tabs representing activities.
   -- Empty face --
```
And the result is that the tab-bar tabs have their standard appearance, as if `activities-tabs-mode` were not enabled.

Are you sure you set the face the same way?

If so, I'll probably have to add an option to just disable the tab face function.

> 
> Thank you for an otherwise very interesting and useful package.

Thanks for your feedback.

**Comment by ericsfraga** [comment]
Apologies for the noise. Setting activities-tab-face to nil (or () as I did) works just fine. Thank you.

**Comment by alphapapa** [comment]
Ok, that's good.  :)  Thanks.
