### ISSUE TITLE
Compilation warning about buffer-local-value

### ISSUE THREAD

**Issue by bkaestner** [alphapapa/activities.el#21]
During `M-x package-install activities.el`, I got the following warnings:

```
In toplevel form:
activities-list.el: Warning: `buffer-local-value' is an obsolete generalized variable.

In toplevel form:
activities.el:653:34: Warning: `buffer-local-value' is an obsolete generalized variable.
```

I investigated a bit, and it seems like `buffer-local-value has been made obsolete with Emacs 29.1 (found within NEWS):

> ## Many seldom-used generalized variables have been made obsolete.
> Emacs has a number of rather obscure generalized variables defined, […]
> […]
> These never caught on and have been made obsolete. […]
>
> The following generalized variables have been made obsolete:
> 'buffer-file-name', ***'buffer-local-value'***, […] [emphasis mine]

This seems to affect the following loop:

```lisp
              (cl-loop for (variable . value) in local-variable-map
                       do (setf (buffer-local-value variable (current-buffer)) value))))
```
I'm not too familiar with buffer-local-variables set without `setq-local`, but
```lisp
              (cl-loop for (variable . value) in local-variable-map
                       do (set (make-local-variable variable) value))))
```
might already fix that?

Hope that helps!

**Comment by alphapapa** [comment]
Hello,

I already lint my packages thoroughly, having written a tool to do so: https://github.com/alphapapa/makem.sh

That warning is an unfortunate vestige of a poor decision made without discussion among Emacs developers.  It is invalid, but will persist in the wild for years to come, resulting in reports like this.  Please see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=65555

**Comment by bkaestner** [comment]
> Please see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=65555

Thanks for the link. I've updated to 29.2 and can confirm that the warning is gone. Sorry for the noise, I had checked NEWS's 29.2 entries, but there wasn't a remark about `buffer-local-value` getting reinstated, otherwise I would have checked 29.2 earlier :/

>  It is invalid, but will persist in the wild for years to come, 

Fortunately, there's only ~6 months of 29.1 in the wild, and 29.2 should be early enough for the inclusion in Ubuntu 24.04.

But at the very least, you now have a reference issue that you can just point to if someone else reports this :)

**Comment by alphapapa** [comment]
I think you're the second or third to report it since then, but I've lost count.

Now to repeat this process for all the other ones I will (eventually) request be un-obsoleted...
