### ISSUE TITLE
Ability to open/switch to activities in same Emacs frame?

### ISSUE THREAD

**Issue by Icy-Thought** [alphapapa/activities.el#22]
To begin with, I want to express my gratitude for developing such an amazing package! Now, I want to ask if it would be possible to implement a feature that would allow us to open/switch to activities in the same frame without creating one. 

I am more accustomed to having one scratchpad buffer of Emacs and calling it on demand and later hiding than I am used to having new frames created. (a habit I perhaps should get rid of, hehe) Therefore having the ability to keep using my scratchpad buffer would be delightful!

**Comment by akurth** [comment]
I second that idea. I’m running emacs daemon and a number of emacsclient frames with fixed sizes. It would be great to be able to reuse the same frame without having to resort to activities-tabs-mode.

**Comment by alphapapa** [comment]
Ok, it seems like users who don't use tab-bar-mode generally prefer to use a single frame at a time and don't want a new frame to be made when resuming an activity.  So I will make that the default behavior in the next version.

Thanks.

**Comment by jdtsmith** [comment]
But some of us like the frames too so please leave as an option!

**Comment by alphapapa** [comment]
Please see the new option added in https://github.com/alphapapa/activities.el/commit/c7150af8b2222746f0fa7771dce5a5c8f055c3a2 and let me know how it works for you.

**Comment by Icy-Thought** [comment]
I have done some limited testing as of now (partially broken config), and what I can say is thank you! The new change is wonderful!!
