### ISSUE TITLE
Enable wiki to share community accomplishments?

### ISSUE THREAD

**Issue by Icy-Thought** [alphapapa/activities.el#23]
As title mentions. And allow me to be the first one to share my accomplishment of creating a simple `hydra` menu for quicker access to `activities` many useful functions!

Preview:
![Workspace 2024-02-04 22:19:35](https://github.com/alphapapa/activities.el/assets/53710398/5ce9aa13-437c-45d9-9694-f44c0fc40c4b)

Requirements:
- https://github.com/rainstormstudio/nerd-icons.el
- https://github.com/jerrypnz/major-mode-hydra.el
- https://github.com/Ladicle/hydra-posframe

Snippet to create the titles of our pretty-hydra's:
> [!NOTE]  
> I do not recall where I got this snippet from but the credits belong to the original author who wrote this snippet!

```emacs-lisp
(cl-defun pretty-hydra-title (title &optional icon-type icon-name
                                      &key face height v-adjust)
    "Add an icon to our pretty-hydra title(s)."
    (let ((face (or face `(:inherit hydra-face-pink :height 1.2 :slant italic)))
          (height (or height 1.2))
          (v-adjust (or v-adjust 0.0)))
      (concat
       (when (and (display-graphic-p) icon-type icon-name)
         (let ((f (intern (format "nerd-icons-%s" icon-type))))
           (when (fboundp f)
             (concat
              (apply f (list icon-name :face face :height height :v-adjust v-adjust))
              "  "))))
       (propertize title 'face face))))
```

```emacs-lisp
(with-eval-after-load 'pretty-hydra
  (pretty-hydra-define activities-hydra
    (:title (pretty-hydra-title "──｢ Utilities: Activities ｣──" 'mdicon "nf-md-file_tree")
            :color teal :quit-key "q")
    ("Main"
     (("l"   activities-list   "List")
      ("RET" activities-switch "Switch"))
     "Working"
     (("n"   activities-new     "Create")
      ("k"   activities-kill    "Kill")
      ("u"   activities-revert  "Revert"))
     "Breaktime"
     (("s"   activities-suspend "Suspend")
      ("r"   activities-resume  "Resume")))))
```

**Comment by alphapapa** [comment]
Ok, I turned it on and enabled public access for now.  Feel free to add what you like.  Thanks.

**Comment by Icy-Thought** [comment]
I will soon migrate the `pretty-hydra` of mine to the wiki then! Should I close this issue?

**Comment by Icy-Thought** [comment]
The new page can be found at: https://github.com/alphapapa/activities.el/wiki/Activities-Hydra. Feedback is obviously accepted since it's my very first time writing a wiki-page!

**Comment by alphapapa** [comment]
Looks nice.  Thanks.

**Comment by Icy-Thought** [comment]
Glad you liked it!
