### ISSUE TITLE
`C-x C-a' prefix is default key-prefix for dape and gud (gdb-mi)

### ISSUE THREAD

**Issue by jeff-phil** [alphapapa/activities.el#32]
Tag: discussion

The [dape](https://github.com/svaante/dape) package which also includes [gud](https://www.gnu.org/software/emacs/manual/html_node/emacs/Commands-of-GUD.html) or `gdb-mi` uses `C-x C-a` as their default prefix.

I prefer to use `C-x C-a` for `activities`. In case others struggle to change this for `dape` and `gud`, in `dape` `use-package` need to set in `:preface` the prefix keys for both in order to keep them from removing activities.

Example where I set prefix to `C-x D`:

```emacs-lisp
  (use-package dape
    :preface
    ;; These need to be set at prefix, or else interferes with `C-x C-a` of `activities'
    ;; This is `C-x D prefix`
    (setq dape-key-prefix "\C-xD")
    (setq gud-key-prefix "\C-xD")) ;; gdb-mi
```

**Comment by jeff-phil** [comment]
Yes, will do!  I've opened a dape PR to update the README for the default config to note this.

**Comment by alphapapa** [comment]
Thanks!
