### ISSUE TITLE
Optionally do not `set-frame-name`

### ISSUE THREAD

**Issue by jdtsmith** [alphapapa/activities.el#33]
Many people customize the frame title to include other information (like full path).  It would be great if `activities` had an option _not_ to set the frame name.  Then you can always include an `:eval` in `frame-title-format` with `(activities-name-for (activities-current))`.

**Comment by jdtsmith** [comment]
Is there an analog for tab names too?  Probably one config option should target both.

**Comment by alphapapa** [comment]
I can't think of a scenario in which a tab shouldn't be renamed; otherwise the user wouldn't know it's associated with an activity.

Frames are different because they are shown and activated by programs outside of Emacs, and renaming a frame can affect how it's grouped with other frames.

**Comment by jdtsmith** [comment]
See #38.
