### ISSUE TITLE
Optionally kill associated buffers when suspending an activity

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/activities.el#35]
It would be nice to optionally kill buffers that are associated with an activity when suspending the activity (buffers that are strictly associated with it, i.e. ones that have only been shown in its frame/tab).

**Comment by Meagainnpc** [comment]
> It would be nice to optionally kill buffers that are associated with an activity when suspending the activity (buffers that are strictly associated with it, i.e. ones that have only been shown in its frame/tab).
