### ISSUE TITLE
[feature request] add an mode-line indicator as current activity name.

### ISSUE THREAD

**Issue by stardiviner** [alphapapa/activities.el#49]
My daily workflow will open many different activities about 10 activities. But sometime want to know which activity currently after I leave for a while.

Can activities.el provide a minor-mode `:lighter` indicator in mode-line?

I tried to use existing variable to got current activty but failed with bellowing code:

```elisp
(add-to-list 'mode-line-misc-info
               '(activities-mode (:eval (concat
                                         "[※ "
                                         (activities-activity-name
                                          (cdar (cl-remove-if-not #'activities-activity-last ; FIXME: not current activity.
                                                                  activities-activities
                                                                  :key #'cdr)))
                                         "]"))))
```

**Comment by alphapapa** [comment]
This could be done, but the current activity is already shown in the frame/tab name.  Does that not work for you?

**Comment by stardiviner** [comment]
I know `activities-tabs-mode`, but I don't want to show all opened activies, so I have not enabled this mode.
BTW, I tried the `activities-tabs-mode`, but I found the color for current activty tab is not different with other tabs. I think you can improve it. Although I still don't want to use the tab-bar.

**Comment by alphapapa** [comment]
> I know `activities-tabs-mode`, but I don't want to show all opened activies, so I have not enabled this mode. 

I'm not sure what you mean.  If an activity is opened, it is visible, either as a frame or a tab, depending on whether you're using `activities-tabs-mode`.  There is no such thing as a non-visible, opened activity.  (Within the library, the term `active` is used; see predicate `activities-activity-active-p`.)

> BTW, I tried the `activities-tabs-mode`, but I found the color for current activty tab is not different with other tabs. I think you can improve it. 

Please see the definition of the face `activities-tabs`.  Its appearance depends on your theme, and you can customize it to your liking.

> Thanks for this good extension, I improved the workspace management better than eyebrowse with better performance.

Thanks.

**Comment by stardiviner** [comment]
> > I know `activities-tabs-mode`, but I don't want to show all opened activies, so I have not enabled this mode.
> 
> I'm not sure what you mean. If an activity is opened, it is visible, either as a frame or a tab, depending on whether you're using `activities-tabs-mode`. There is no such thing as a non-visible, opened activity. (Within the library, the term `active` is used; see predicate `activities-activity-active-p`.)

<img width="1079" alt="image" src="https://github.com/alphapapa/activities.el/assets/378699/cd1a910d-c2de-4128-9b16-2bbc4b0409fd">

I mean I don't like this way which showing all active activities is a little noisy for me which don't use mouse to click on those activities tabs. That's why I don't enable `activities-tabs-mode`. Seeing all active activities in completing from `activities-switch` is ok. An indicator in mode-line showing current activity will be helpful.

> > BTW, I tried the `activities-tabs-mode`, but I found the color for current activty tab is not different with other tabs. I think you can improve it.
> 
> Please see the definition of the face `activities-tabs`. Its appearance depends on your theme, and you can customize it to your liking.
Right. Habit on no much customization. I will do this font customization.

**Comment by alphapapa** [comment]
@stardiviner I understand, you don't want to use tabs-mode.  That's fine.  So my question is, what about the way the activity is shown in the frame title?

To be clear, I'm not opposed to adding an optional mode line thing, I'm just trying to understand how the frame title feature works for you first.  Thanks.

**Comment by stardiviner** [comment]
Hmm, frame title indeed is an option for my purpose. I still prefer mode-line indicator. I think adding a function for showing current active activity is the API. No matter adding activities indicator to frame title or mode-line is easy in package. They can be an user option to control and disabled by default. WDYT?

**Comment by alphapapa** [comment]
There is already a function that returns the current activity.

Anyway, I'll add this to the to-do list.  Patches welcome in the meantime.

**Comment by stardiviner** [comment]
> There is already a function that returns the current activity.

I found setting frame title in code `activities--switch`:
```elisp
(when activities-set-frame-name
    (set-frame-name (activities-name-for activity)))
```
I originally try to find some function or variable like `(project-root)` (reference my first comment code snippet). Something like this:
```elisp
(defun activities--switch (activity)
  "Switch to ACTIVITY.
Select's ACTIVITY's frame, making a new one if needed.  Its state
is not changed."
  (if (activities-activity-active-p activity)
      (select-frame (activities--frame activity))
    (pcase activities-resume-into-frame
      ('current nil)
      ('new (select-frame (make-frame `((activity . ,activity)))))))
  (unless activities-saving-p
    ;; HACK: Don't raise the frame when saving the activity's state.
    ;; (I don't love this solution, largely because it only applies
    ;; when not using `activities-tabs-mode', but it will do for now.)
    (raise-frame))
  ;; set current activity variable
  (setq activities-current-activty activity) ; NOTE: or make it as a function?
  (when activities-set-frame-name
    (set-frame-name (activities-name-for activity))))
```

> Anyway, I'll add this to the to-do list. Patches welcome in the meantime.

Thanks a lot.

**Comment by stardiviner** [comment]
Update: Ah, I found function `activities-current`,  but it returns `nil`.
