### ISSUE TITLE
Error restoring last of 4 split windows of org-ql view buffers

### ISSUE THREAD

**Issue by ParetoOptimalDev** [alphapapa/activities.el#51]
I have an org-ql as part of "My daily review" activity called "Tasks done in the past week" that uses this query:

```
(or (and (todo "DONE") (closed :from -7)))
```

If I:

- Evaluate `(org-ql-view "Finished past week")` in the scratch buffer
- Call `activities-new`, type "new activity"
- close emacs
- open emacs, `activities-resume`, "new activity"

Things work as expected.

However in my case where I have 4 different org-ql views for some reason this one fails to load and I see this buffer instead:

```
Activities was unable to get a buffer named: *Org QL View: Finished past week*

It is likely that this buffer's major mode does not support the `bookmark' system, so it can't be restored properly.  Please ask the major mode's maintainer to add bookmark support.

If this is not the case, please report this error to the `activities' maintainer.
```

My only guess is that perhaps something about `(closed :from -7)` makes it harder to resume because those are translated to actual dats at some point.

I'm guessing you need to see the actual full AST of my activity to debug what's going on here, but I don't currently know how I can get that.

Note that if I manually call `(org-ql-view "Finished past week")` before resuming the activity then the buffer is there just fine. I'm assuming this is because no resume logic happens and it just uses the already open buffer.

Please advise.

**Comment by alphapapa** [comment]
I already use `activities` for similar purposes and it works for me.  I'd suggest using https://github.com/alphapapa/with-emacs.sh to try to reproduce the problem in a clean configuration with the latest version of all packages.
