### ISSUE TITLE
Tab bar disappears after calling (activities-tabs-mode 1) twice 

### ISSUE THREAD

**Issue by fuzy112** [alphapapa/activities.el#7]
After calling `(activities-tabs-mode 1)` twice, tab bar will disappear.

It seems that both `tab-bar-tab-face-function` and `activities-tabs-tab-bar-tab-face-function-original` are set to `#'activities-tabs--tab-bar-tab-face-function`.

**Comment by alphapapa** [comment]
Yeah, I've been noticing this myself, and I haven't been able to figure out the problem yet.  Probably been staring at the screen for too long.
