### ISSUE TITLE
Configuring tabs

### ISSUE THREAD

**Issue by bmp** [alphapapa/activities.el#95]
Hello and thank you for creating this package. My Emacs is slowly turning into alphapapa Emacs (I have buffler, ement, org-ql and now activities). I have the following configuration:

```
  (use-package activities
    :ensure (:fetcher github :repo "alphapapa/activities.el")
    :init
    (activities-mode)
    (activities-tabs-mode)
    ;; Prevent `edebug' default bindings from interfering.
    (setq edebug-inhibit-emacs-lisp-mode-bindings t)
    ;; set tab bar properties
    (setq tab-bar-close-button-show nil) ;; Remove the button for closing the tab
    (setq tab-bar-format '(tab-bar-format-history tab-bar-format-tabs tab-bar-separator))
    (set-face-attribute 'tab-bar nil :height 1.4)

    :bind
    (("C-x C-a C-n" . activities-new)
     ("C-x C-a C-d" . activities-define)
     ("C-x C-a C-a" . activities-resume)
     ("C-x C-a C-s" . activities-suspend)
     ("C-x C-a C-k" . activities-kill)
     ("C-x C-a RET" . activities-switch)
     ("C-x C-a b" . activities-switch-buffer)
     ("C-x C-a g" . activities-revert)
     ("C-x C-a l" . activities-list)))
```

And this is how the tabs look like:
![Screenshot_20240603_182330](https://github.com/alphapapa/activities.el/assets/1095177/2715ec5c-adab-4dd4-b439-a07b1c15571c)

I have successfully modified it to remove the close tab button, changed the size of the font for the text in the tab. 

Could you please let me know how I can do the following?
1. Change the 'alpa' symbol to a specifically an icon that I can set (either for each activity or a generic symbol for all activities like 'alpha' currently)? 
2. Change the font (I prefer serif fonts)
3. Potentially have fixed width for the tabs rather than adaptive to the size of the name
4. Set the tab bar size, and a different size for the font. Currently, the font size is dictating the tab bar size.

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad that this and some of my other packages are useful to you.

For #1, please see the customization options.  `M-x customize-group RET activities`.

For the other questions, these are not about Activities but about Emacs.  I'm afraid that I can't offer support for general questions about Emacs here, as I simply don't have the time.  Please make use of appropriate forums and resources, such as searching the web (which should provide answers to these questions), https://old.reddit.com/r/emacs, etc.  Thanks.
